// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eryfefupxjabrpvqabkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyeWZlZnVweGphYnJwdnFhYmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2OTkwNjEsImV4cCI6MjA1MzI3NTA2MX0.idzabndiw3gmvfyacYqDRwNr8HU-Er-5dP3PhyFmMG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);